# Module 3: Data Structures Assignments
## Lesson 3.2: Tuples
### Assignment 1: Creating and Accessing Tuples

Create a tuple with the first 10 positive integers. Print the tuple.

### Assignment 2: Accessing Tuple Elements

Print the first, middle, and last elements of the tuple created in Assignment 1.

### Assignment 3: Tuple Slicing

Print the first three elements, the last three elements, and the elements from index 2 to 5 of the tuple created in Assignment 1.

### Assignment 4: Nested Tuples

Create a nested tuple representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

### Assignment 5: Tuple Concatenation

Concatenate two tuples: (1, 2, 3) and (4, 5, 6). Print the resulting tuple.

### Assignment 6: Tuple Methods

Create a tuple with duplicate elements and count the occurrences of an element. Find the index of the first occurrence of an element in the tuple.

### Assignment 7: Unpacking Tuples

Create a tuple with 5 elements and unpack it into 5 variables. Print the variables.

### Assignment 8: Tuple Conversion

Convert a list of the first 5 positive integers to a tuple. Print the tuple.

### Assignment 9: Tuple of Tuples

Create a tuple containing 3 tuples, each with 3 elements. Print the tuple of tuples.

### Assignment 10: Tuple and List

Create a tuple with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a tuple. Print the resulting tuple.

### Assignment 11: Tuple and String

Create a tuple with the characters of a string. Join the tuple elements into a single string. Print the string.

### Assignment 12: Tuple and Dictionary

Create a dictionary with tuple keys and integer values. Print the dictionary.

### Assignment 13: Nested Tuple Iteration

Create a nested tuple and iterate over the elements, printing each element.

### Assignment 14: Tuple and Set

Create a tuple with duplicate elements. Convert it to a set to remove duplicates and print the resulting set.

### Assignment 15: Tuple Functions

Write functions that take a tuple and return the minimum, maximum, and sum of the elements. Print the results for a sample tuple.

In [ ]:
### Assignment 1: Creating and Accessing Tuples

## Create a tuple with the first 10 positive integers. Print the tuple.

tup_10_nos = (1,2,3,4,5,6,7,8,9,10)
print(tup_10_nos)  # (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [ ]:
### Assignment 2: Accessing Tuple Elements

## Print the first, middle, and last elements of the tuple created in Assignment 1.

print(tup_10_nos[0])
print(tup_10_nos[4])
print(tup_10_nos[-1])

In [ ]:
### Assignment 3: Tuple Slicing

## Print the first three elements, the last three elements, and the elements from index 2 to 5 of the tuple created in Assignment 1.

print(tup_10_nos[:3])  # (1, 2, 3)
print(tup_10_nos[7:])  # (8, 9, 10)
print(tup_10_nos[2:6])  # (3, 4, 5, 6)

In [ ]:
### Assignment 4: Nested Tuples

## Create a nested tuple representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

matrix_tup = (
    (1,2,3),
    (4,5,6),
    (7,8,9)
)

print(matrix_tup[1][2])  # 6

In [ ]:
### Assignment 5: Tuple Concatenation

## Concatenate two tuples: (1, 2, 3) and (4, 5, 6). Print the resulting tuple.

t1 = (1,2,3)
t2 = (4,5,6)
print(t1+t2)  # (1, 2, 3, 4, 5, 6)

In [ ]:
### Assignment 6: Tuple Methods

## Create a tuple with duplicate elements and count the occurrences of an element. Find the index of the first occurrence of an element in the tuple.

dup_tup = ('a', 'c', 'd', 'e', 'c', 'f')
print(dup_tup.count('c'))  # 2
print(dup_tup.index('c'))  # 1

In [ ]:
### Assignment 7: Unpacking Tuples

## Create a tuple with 5 elements and unpack it into 5 variables. Print the variables.


tup_5 = (10, 20, 30, 40, 50)
a, b, c, d, e = tup_5
print(a, b, c, d, e)  # 10 20 30 40 50

In [ ]:
### Assignment 8: Tuple Conversion

## Convert a list of the first 5 positive integers to a tuple. Print the tuple.

lst_5 = (1,2,3,4,5)
tuple_5 = tuple(lst_5)
print(tuple_5)  # (1, 2, 3, 4, 5)

In [ ]:
### Assignment 9: Tuple of Tuples

## Create a tuple containing 3 tuples, each with 3 elements. Print the tuple of tuples.

tup_tup = (
    ('a', 'b', 'c'),
    ('d', 'e', 'f'),
    ('g', 'h', 'i')
)

print(tup_tup[0])
print(tup_tup[1])
print(tup_tup[2])

'''
('a', 'b', 'c')
('d', 'e', 'f')
('g', 'h', 'i')
'''

In [ ]:
### Assignment 10: Tuple and List

## Create a tuple with the first 5 positive integers. Convert it to a list, append the number 6, and convert it back to a tuple. Print the resulting tuple.

new_tup_5 = (1,2,3,4,5)
new_lst_5 = list(new_tup_5)
new_lst_5.append(6)
new_new_tup_5 = tuple(new_lst_5)
print(new_new_tup_5)  # (1, 2, 3, 4, 5, 6)

In [ ]:
### Assignment 11: Tuple and String

## Create a tuple with the characters of a string. Join the tuple elements into a single string. Print the string.

tup_str = ('n', 'i', 's', 'h', 'a', 'n', 'k')

# Join tuple elements into a string
result = ''.join(tup_str)

# Print the string
print(result)  # nishank

In [ ]:
### Assignment 12: Tuple and Dictionary

## Create a dictionary with tuple keys and integer values. Print the dictionary.

tup_dict = {
    (1, 2): 10,
    (3, 4): 20,
    (5, 6): 30
}

# Print the dictionary
print(tup_dict)  # {(1, 2): 10, (3, 4): 20, (5, 6): 30}

In [ ]:
### Assignment 13: Nested Tuple Iteration

## Create a nested tuple and iterate over the elements, printing each element.

new_nested_tup = ((1,2,3), (10,20,30), (100,200,300))
for sub_tup in new_nested_tup:
    for item in sub_tup:
        print(item, end = " ")
    print()

'''
1 2 3 
10 20 30 
100 200 300 
'''

In [ ]:
### Assignment 14: Tuple and Set

## Create a tuple with duplicate elements. Convert it to a set to remove duplicates and print the resulting set.

my_tup = ('n', 'i', 's', 'h', 'a', 'n', 'k')

my_set = set(my_tup)
print(my_set)  # {'a', 'i', 'n', 'k', 'h', 's'}

In [ ]:
### Assignment 15: Tuple Functions

## Write functions that take a tuple and return the minimum, maximum, and sum of the elements. Print the results for a sample tuple.

def minimum(original_tup):
    min_val = min(original_tup)
    return min_val

def maximum(original_tup):
    max_val = max(original_tup)
    return max_val

def sum(original_tup):
    sum = 0
    for tup in original_tup:
        sum += tup
    return sum

original_tup = (1,2,3,4,5,6,7,8,9,10)

print(f"Minimum value is: {minimum(original_tup)}")
print(f"Maximum value is: {maximum(original_tup)}")
print(f"Sum is: {sum(original_tup)}")

'''
Minimum value is: 1
Maximum value is: 10
Sum is: 55
'''